// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2WQT88alCYgH7gLrdQ6jaiAyn-R3EFbs',
    appId: '1:1015021526856:web:7dc4d3439142d1041a5d7d',
    messagingSenderId: '1015021526856',
    projectId: 'khaata-69a30',
    authDomain: 'khaata-69a30.firebaseapp.com',
    storageBucket: 'khaata-69a30.firebasestorage.app',
    measurementId: 'G-GNNC3J9RQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7raBL2PB2QHWpwIUUjKapuW9RhRlFQHI',
    appId: '1:1015021526856:android:bc56a89fc59888a91a5d7d',
    messagingSenderId: '1015021526856',
    projectId: 'khaata-69a30',
    storageBucket: 'khaata-69a30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4VEA19EU9_OoYmBEwMCrsiqbhcjvt7hQ',
    appId: '1:1015021526856:ios:83df024177ae420d1a5d7d',
    messagingSenderId: '1015021526856',
    projectId: 'khaata-69a30',
    storageBucket: 'khaata-69a30.firebasestorage.app',
    iosBundleId: 'com.example.khatha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4VEA19EU9_OoYmBEwMCrsiqbhcjvt7hQ',
    appId: '1:1015021526856:ios:83df024177ae420d1a5d7d',
    messagingSenderId: '1015021526856',
    projectId: 'khaata-69a30',
    storageBucket: 'khaata-69a30.firebasestorage.app',
    iosBundleId: 'com.example.khatha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2WQT88alCYgH7gLrdQ6jaiAyn-R3EFbs',
    appId: '1:1015021526856:web:24b8e415d8aaa06f1a5d7d',
    messagingSenderId: '1015021526856',
    projectId: 'khaata-69a30',
    authDomain: 'khaata-69a30.firebaseapp.com',
    storageBucket: 'khaata-69a30.firebasestorage.app',
    measurementId: 'G-1THKBTV9XG',
  );
}
