// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ZCyFHtSt-XnFofGFxofQUJgX0OtJcog',
    appId: '1:119567932403:web:4fa92277655b0b50a91086',
    messagingSenderId: '119567932403',
    projectId: 'khaata-42b18',
    authDomain: 'khaata-42b18.firebaseapp.com',
    storageBucket: 'khaata-42b18.firebasestorage.app',
    measurementId: 'G-RL0HMMWJHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWwG-t0JdGQ98rmkIsWQSZsCRRJhzMoAw',
    appId: '1:119567932403:android:0825bf2ed995c992a91086',
    messagingSenderId: '119567932403',
    projectId: 'khaata-42b18',
    storageBucket: 'khaata-42b18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ4nVc-nMlEwh6cQkH4dupiv84rkaVT-o',
    appId: '1:119567932403:ios:9272b715df061957a91086',
    messagingSenderId: '119567932403',
    projectId: 'khaata-42b18',
    storageBucket: 'khaata-42b18.firebasestorage.app',
    iosBundleId: 'com.example.khatha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ4nVc-nMlEwh6cQkH4dupiv84rkaVT-o',
    appId: '1:119567932403:ios:9272b715df061957a91086',
    messagingSenderId: '119567932403',
    projectId: 'khaata-42b18',
    storageBucket: 'khaata-42b18.firebasestorage.app',
    iosBundleId: 'com.example.khatha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6ZCyFHtSt-XnFofGFxofQUJgX0OtJcog',
    appId: '1:119567932403:web:8445b744d29efd63a91086',
    messagingSenderId: '119567932403',
    projectId: 'khaata-42b18',
    authDomain: 'khaata-42b18.firebaseapp.com',
    storageBucket: 'khaata-42b18.firebasestorage.app',
    measurementId: 'G-KVTNVC6W67',
  );
}
